# path = "C:/Users/kunal/Documents/BoekeLabResearch/diffusion/house_keeping_promoter_generation/data/new_promoters.txt"
# save_path = "C:/Users/kunal/Documents/BoekeLabResearch/diffusion/house_keeping_promoter_generation/data/temp.out"

# with open(path, 'r') as file:
#     lines = file.readlines()
#     save = []
#     for sequence in lines:
#         save.append((sequence.strip(), 5))

# with open(save_path, 'w') as file:
#     file.write(json.dumps(save))
# import numpy as np
# a = np.load("C:/Users/kunal/Documents/npy_data/save_data_house_keeping_promoter.npy")
# print(a.shape)

#s = "ACAACTGGCCAGGTTCCCTGGCCTCCCGGGTCCCTGCATCCCCCGCATCCCCGTCCGCAGCCGTGAACTTGAGCCCCCCTCCATCAGAGGTTGCGAGCGTCCGCCCGCTCGCGGCAGCCACCGTCACTAGACAGTCAAACCCCAAGACGTCAGCCCACAATGCACCGGGCGGGCCGGGAAAAACGGCCCGGGGAGGGGACCGGGGAAGAGAGGGCCGAGAGGCGTGCGGCAGGGGGGAGGGTAGGAGAAAGAAGGGCCCGACTGTAGGAGGGCAGCGGAGCATTACCTCATCCCGTGAGCCTCCGCGGGCCCAGAGAAGAATCTTCTAGGGTGGAGTCTCCATGGTGACGGGCGGGCCCGCCCCCCTGAGAGCGACGCGAGCCAATGGGAAGGCCTTGGGGTGACATCATGGGCTATTTTTAGGGGTTGACTGGTAGCAGATAAGTGTTGAGCTCGGGCTGGATAAGGGCTCAGAGTTGCACTGAGTGTGGCTGAAGCAGCGAGGCGGGAGTGGAGGTGCGCGGAGTCAGGCAGACAGACAGACACAGCCAGCCAGCCAGGTCGGCAGTATAGTCCGAACTGCAAATCTTATTTTCTTTT"
#neg = "ACAGGGCTTGCAGGTGCTGATGCCAGAAGCTTCTGTGCCATTGCATTAAAGACTTGTCATTTGATCCATGTTCAAGACCCTTGAGATAAGGAAAACGAAGCACAGAGCAATTAAATAACTTGCCCAAGATCGCCCAAGATCACCCAAGATGTCCGGCTGAAGTTCTTAACCATTACCTTACACTAATCAACAGCAACAATAATAATAACCACCTTTCTAGGATGCAAATTATGTTCCAAGAACTTTCATTATTTCATTACATCTGCATAGCCCCAAGAGTAAATAATATCCTGTTCTATT"
#print(s[300: -50])
#print(neg[25: -25])